export default {
  'ar.abdullahbasfar': 'عبد الله بصفر',
  'ar.abdurrahmaansudais': 'عبدالرحمن السديس',
  'ar.abdulsamad': 'عبدالباسط عبدالصمد',
  'ar.shaatree': 'أبو بكر الشاطري',
  'ar.ahmedajamy': 'أحمد بن علي العجمي',
  'ar.alafasy': 'مشاري العفاسي',
  'ar.hanirifai': 'هاني الرفاعي',
  'ar.husary': 'محمود خليل الحصري',
  'ar.husarymujawwad': 'محمود خليل الحصري (المجود)',
  'ar.hudhaify': 'علي بن عبدالرحمن الحذيفي',
  'ar.ibrahimakhbar': 'إبراهيم الأخضر',
  'ar.mahermuaiqly': 'ماهر المعيقلي',
  'ar.muhammadayyoub': 'محمد أيوب',
  'ar.muhammadjibreel': 'محمد جبريل',
  'ar.saoodshuraym': 'سعود الشريم',
  'ar.parhizgar': 'شهریار پرهیزگار',
  'ar.aymanswoaid': 'أيمن سويد',
}
