export default [
  {
    id: 1,
    name: 'سُورَةُ الْفَاتِحَةِ',
    numberOfAyahs: 7,
    isMeccan: true,
  },
  {
    id: 2,
    name: 'سُورَةُ البَقَرَةِ',
    numberOfAyahs: 286,
    isMeccan: false,
  },
  {
    id: 3,
    name: 'سُورَةُ آلِ عِمۡرَانَ',
    numberOfAyahs: 200,
    isMeccan: false,
  },
  {
    id: 4,
    name: 'سُورَةُ النِّسَاءِ',
    numberOfAyahs: 176,
    isMeccan: false,
  },
  {
    id: 5,
    name: 'سُورَةُ المَائِدَةِ',
    numberOfAyahs: 120,
    isMeccan: false,
  },
  {
    id: 6,
    name: 'سُورَةُ الأَنۡعَامِ',
    numberOfAyahs: 165,
    isMeccan: true,
  },
  {
    id: 7,
    name: 'سُورَةُ الأَعۡرَافِ',
    numberOfAyahs: 206,
    isMeccan: true,
  },
  {
    id: 8,
    name: 'سُورَةُ الأَنفَالِ',
    numberOfAyahs: 75,
    isMeccan: false,
  },
  {
    id: 9,
    name: 'سُورَةُ التَّوۡبَةِ',
    numberOfAyahs: 129,
    isMeccan: false,
  },
  {
    id: 10,
    name: 'سُورَةُ يُونُسَ',
    numberOfAyahs: 109,
    isMeccan: true,
  },
  {
    id: 11,
    name: 'سُورَةُ هُودٍ',
    numberOfAyahs: 123,
    isMeccan: true,
  },
  {
    id: 12,
    name: 'سُورَةُ يُوسُفَ',
    numberOfAyahs: 111,
    isMeccan: true,
  },
  {
    id: 13,
    name: 'سُورَةُ الرَّعۡدِ',
    numberOfAyahs: 43,
    isMeccan: false,
  },
  {
    id: 14,
    name: 'سُورَةُ إِبۡرَاهِيمَ',
    numberOfAyahs: 52,
    isMeccan: true,
  },
  {
    id: 15,
    name: 'سُورَةُ الحِجۡرِ',
    numberOfAyahs: 99,
    isMeccan: true,
  },
  {
    id: 16,
    name: 'سُورَةُ النَّحۡلِ',
    numberOfAyahs: 128,
    isMeccan: true,
  },
  {
    id: 17,
    name: 'سُورَةُ الإِسۡرَاءِ',
    numberOfAyahs: 111,
    isMeccan: true,
  },
  {
    id: 18,
    name: 'سُورَةُ الكَهۡفِ',
    numberOfAyahs: 110,
    isMeccan: true,
  },
  {
    id: 19,
    name: 'سُورَةُ مَرۡيَمَ',
    numberOfAyahs: 98,
    isMeccan: true,
  },
  {
    id: 20,
    name: 'سُورَةُ طه',
    numberOfAyahs: 135,
    isMeccan: true,
  },
  {
    id: 21,
    name: 'سُورَةُ الأَنبِيَاءِ',
    numberOfAyahs: 112,
    isMeccan: true,
  },
  {
    id: 22,
    name: 'سُورَةُ الحَجِّ',
    numberOfAyahs: 78,
    isMeccan: false,
  },
  {
    id: 23,
    name: 'سُورَةُ المُؤۡمِنُونَ',
    numberOfAyahs: 118,
    isMeccan: true,
  },
  {
    id: 24,
    name: 'سُورَةُ النُّورِ',
    numberOfAyahs: 64,
    isMeccan: false,
  },
  {
    id: 25,
    name: 'سُورَةُ الفُرۡقَانِ',
    numberOfAyahs: 77,
    isMeccan: true,
  },
  {
    id: 26,
    name: 'سُورَةُ الشُّعَرَاءِ',
    numberOfAyahs: 227,
    isMeccan: true,
  },
  {
    id: 27,
    name: 'سُورَةُ النَّمۡلِ',
    numberOfAyahs: 93,
    isMeccan: true,
  },
  {
    id: 28,
    name: 'سُورَةُ القَصَصِ',
    numberOfAyahs: 88,
    isMeccan: true,
  },
  {
    id: 29,
    name: 'سُورَةُ العَنكَبُوتِ',
    numberOfAyahs: 69,
    isMeccan: true,
  },
  {
    id: 30,
    name: 'سُورَةُ الرُّومِ',
    numberOfAyahs: 60,
    isMeccan: true,
  },
  {
    id: 31,
    name: 'سُورَةُ لُقۡمَانَ',
    numberOfAyahs: 34,
    isMeccan: true,
  },
  {
    id: 32,
    name: 'سُورَةُ السَّجۡدَةِ',
    numberOfAyahs: 30,
    isMeccan: true,
  },
  {
    id: 33,
    name: 'سُورَةُ الأَحۡزَابِ',
    numberOfAyahs: 73,
    isMeccan: false,
  },
  {
    id: 34,
    name: 'سُورَةُ سَبَإٍ',
    numberOfAyahs: 54,
    isMeccan: true,
  },
  {
    id: 35,
    name: 'سُورَةُ فَاطِرٍ',
    numberOfAyahs: 45,
    isMeccan: true,
  },
  {
    id: 36,
    name: 'سُورَةُ يسٓ',
    numberOfAyahs: 83,
    isMeccan: true,
  },
  {
    id: 37,
    name: 'سُورَةُ الصَّافَّاتِ',
    numberOfAyahs: 182,
    isMeccan: true,
  },
  {
    id: 38,
    name: 'سُورَةُ صٓ',
    numberOfAyahs: 88,
    isMeccan: true,
  },
  {
    id: 39,
    name: 'سُورَةُ الزُّمَرِ',
    numberOfAyahs: 75,
    isMeccan: true,
  },
  {
    id: 40,
    name: 'سُورَةُ غَافِرٍ',
    numberOfAyahs: 85,
    isMeccan: true,
  },
  {
    id: 41,
    name: 'سُورَةُ فُصِّلَتۡ',
    numberOfAyahs: 54,
    isMeccan: true,
  },
  {
    id: 42,
    name: 'سُورَةُ الشُّورَىٰ',
    numberOfAyahs: 53,
    isMeccan: true,
  },
  {
    id: 43,
    name: 'سُورَةُ الزُّخۡرُفِ',
    numberOfAyahs: 89,
    isMeccan: true,
  },
  {
    id: 44,
    name: 'سُورَةُ الدُّخَانِ',
    numberOfAyahs: 59,
    isMeccan: true,
  },
  {
    id: 45,
    name: 'سُورَةُ الجَاثِيَةِ',
    numberOfAyahs: 37,
    isMeccan: true,
  },
  {
    id: 46,
    name: 'سُورَةُ الأَحۡقَافِ',
    numberOfAyahs: 35,
    isMeccan: true,
  },
  {
    id: 47,
    name: 'سُورَةُ مُحَمَّدٍ',
    numberOfAyahs: 38,
    isMeccan: false,
  },
  {
    id: 48,
    name: 'سُورَةُ الفَتۡحِ',
    numberOfAyahs: 29,
    isMeccan: false,
  },
  {
    id: 49,
    name: 'سُورَةُ الحُجُرَاتِ',
    numberOfAyahs: 18,
    isMeccan: false,
  },
  {
    id: 50,
    name: 'سُورَةُ قٓ',
    numberOfAyahs: 45,
    isMeccan: true,
  },
  {
    id: 51,
    name: 'سُورَةُ الذَّارِيَاتِ',
    numberOfAyahs: 60,
    isMeccan: true,
  },
  {
    id: 52,
    name: 'سُورَةُ الطُّورِ',
    numberOfAyahs: 49,
    isMeccan: true,
  },
  {
    id: 53,
    name: 'سُورَةُ النَّجۡمِ',
    numberOfAyahs: 62,
    isMeccan: true,
  },
  {
    id: 54,
    name: 'سُورَةُ القَمَرِ',
    numberOfAyahs: 55,
    isMeccan: true,
  },
  {
    id: 55,
    name: 'سُورَةُ الرَّحۡمَٰن',
    numberOfAyahs: 78,
    isMeccan: false,
  },
  {
    id: 56,
    name: 'سُورَةُ الوَاقِعَةِ',
    numberOfAyahs: 96,
    isMeccan: true,
  },
  {
    id: 57,
    name: 'سُورَةُ الحَدِيدِ',
    numberOfAyahs: 29,
    isMeccan: false,
  },
  {
    id: 58,
    name: 'سُورَةُ المُجَادلَةِ',
    numberOfAyahs: 22,
    isMeccan: false,
  },
  {
    id: 59,
    name: 'سُورَةُ الحَشۡرِ',
    numberOfAyahs: 24,
    isMeccan: false,
  },
  {
    id: 60,
    name: 'سُورَةُ المُمۡتَحنَةِ',
    numberOfAyahs: 13,
    isMeccan: false,
  },
  {
    id: 61,
    name: 'سُورَةُ الصَّفِّ',
    numberOfAyahs: 14,
    isMeccan: false,
  },
  {
    id: 62,
    name: 'سُورَةُ الجُمُعَةِ',
    numberOfAyahs: 11,
    isMeccan: false,
  },
  {
    id: 63,
    name: 'سُورَةُ المُنَافِقُونَ',
    numberOfAyahs: 11,
    isMeccan: false,
  },
  {
    id: 64,
    name: 'سُورَةُ التَّغَابُنِ',
    numberOfAyahs: 18,
    isMeccan: false,
  },
  {
    id: 65,
    name: 'سُورَةُ الطَّلَاقِ',
    numberOfAyahs: 12,
    isMeccan: false,
  },
  {
    id: 66,
    name: 'سُورَةُ التَّحۡرِيمِ',
    numberOfAyahs: 12,
    isMeccan: false,
  },
  {
    id: 67,
    name: 'سُورَةُ المُلۡكِ',
    numberOfAyahs: 30,
    isMeccan: true,
  },
  {
    id: 68,
    name: 'سُورَةُ القَلَمِ',
    numberOfAyahs: 52,
    isMeccan: true,
  },
  {
    id: 69,
    name: 'سُورَةُ الحَاقَّةِ',
    numberOfAyahs: 52,
    isMeccan: true,
  },
  {
    id: 70,
    name: 'سُورَةُ المَعَارِجِ',
    numberOfAyahs: 44,
    isMeccan: true,
  },
  {
    id: 71,
    name: 'سُورَةُ نُوحٍ',
    numberOfAyahs: 28,
    isMeccan: true,
  },
  {
    id: 72,
    name: 'سُورَةُ الجِنِّ',
    numberOfAyahs: 28,
    isMeccan: true,
  },
  {
    id: 73,
    name: 'سُورَةُ المُزَّمِّلِ',
    numberOfAyahs: 20,
    isMeccan: true,
  },
  {
    id: 74,
    name: 'سُورَةُ المُدَّثِّرِ',
    numberOfAyahs: 56,
    isMeccan: true,
  },
  {
    id: 75,
    name: 'سُورَةُ القِيَامَةِ',
    numberOfAyahs: 40,
    isMeccan: true,
  },
  {
    id: 76,
    name: 'سُورَةُ الإِنسَانِ',
    numberOfAyahs: 31,
    isMeccan: false,
  },
  {
    id: 77,
    name: 'سُورَةُ المُرۡسَلَاتِ',
    numberOfAyahs: 50,
    isMeccan: true,
  },
  {
    id: 78,
    name: 'سُورَةُ النَّبَإِ',
    numberOfAyahs: 40,
    isMeccan: true,
  },
  {
    id: 79,
    name: 'سُورَةُ النَّازِعَاتِ',
    numberOfAyahs: 46,
    isMeccan: true,
  },
  {
    id: 80,
    name: 'سُورَةُ عَبَسَ',
    numberOfAyahs: 42,
    isMeccan: true,
  },
  {
    id: 81,
    name: 'سُورَةُ التَّكۡوِيرِ',
    numberOfAyahs: 29,
    isMeccan: true,
  },
  {
    id: 82,
    name: 'سُورَةُ الانفِطَارِ',
    numberOfAyahs: 19,
    isMeccan: true,
  },
  {
    id: 83,
    name: 'سُورَةُ المُطَفِّفِينَ',
    numberOfAyahs: 36,
    isMeccan: true,
  },
  {
    id: 84,
    name: 'سُورَةُ الانشِقَاقِ',
    numberOfAyahs: 25,
    isMeccan: true,
  },
  {
    id: 85,
    name: 'سُورَةُ البُرُوجِ',
    numberOfAyahs: 22,
    isMeccan: true,
  },
  {
    id: 86,
    name: 'سُورَةُ الطَّارِقِ',
    numberOfAyahs: 17,
    isMeccan: true,
  },
  {
    id: 87,
    name: 'سُورَةُ الأَعۡلَىٰ',
    numberOfAyahs: 19,
    isMeccan: true,
  },
  {
    id: 88,
    name: 'سُورَةُ الغَاشِيَةِ',
    numberOfAyahs: 26,
    isMeccan: true,
  },
  {
    id: 89,
    name: 'سُورَةُ الفَجۡرِ',
    numberOfAyahs: 30,
    isMeccan: true,
  },
  {
    id: 90,
    name: 'سُورَةُ البَلَدِ',
    numberOfAyahs: 20,
    isMeccan: true,
  },
  {
    id: 91,
    name: 'سُورَةُ الشَّمۡسِ',
    numberOfAyahs: 15,
    isMeccan: true,
  },
  {
    id: 92,
    name: 'سُورَةُ اللَّيۡلِ',
    numberOfAyahs: 21,
    isMeccan: true,
  },
  {
    id: 93,
    name: 'سُورَةُ الضُّحَىٰ',
    numberOfAyahs: 11,
    isMeccan: true,
  },
  {
    id: 94,
    name: 'سُورَةُ الشَّرۡحِ',
    numberOfAyahs: 8,
    isMeccan: true,
  },
  {
    id: 95,
    name: 'سُورَةُ التِّينِ',
    numberOfAyahs: 8,
    isMeccan: true,
  },
  {
    id: 96,
    name: 'سُورَةُ العَلَقِ',
    numberOfAyahs: 19,
    isMeccan: true,
  },
  {
    id: 97,
    name: 'سُورَةُ القَدۡرِ',
    numberOfAyahs: 5,
    isMeccan: true,
  },
  {
    id: 98,
    name: 'سُورَةُ البَيِّنَةِ',
    numberOfAyahs: 8,
    isMeccan: false,
  },
  {
    id: 99,
    name: 'سُورَةُ الزَّلۡزَلَةِ',
    numberOfAyahs: 8,
    isMeccan: false,
  },
  {
    id: 100,
    name: 'سُورَةُ العَادِيَاتِ',
    numberOfAyahs: 11,
    isMeccan: true,
  },
  {
    id: 101,
    name: 'سُورَةُ القَارِعَةِ',
    numberOfAyahs: 11,
    isMeccan: true,
  },
  {
    id: 102,
    name: 'سُورَةُ التَّكَاثُرِ',
    numberOfAyahs: 8,
    isMeccan: true,
  },
  {
    id: 103,
    name: 'سُورَةُ العَصۡرِ',
    numberOfAyahs: 3,
    isMeccan: true,
  },
  {
    id: 104,
    name: 'سُورَةُ الهُمَزَةِ',
    numberOfAyahs: 9,
    isMeccan: true,
  },
  {
    id: 105,
    name: 'سُورَةُ الفِيلِ',
    numberOfAyahs: 5,
    isMeccan: true,
  },
  {
    id: 106,
    name: 'سُورَةُ قُرَيۡشٍ',
    numberOfAyahs: 4,
    isMeccan: true,
  },
  {
    id: 107,
    name: 'سُورَةُ المَاعُونِ',
    numberOfAyahs: 7,
    isMeccan: true,
  },
  {
    id: 108,
    name: 'سُورَةُ الكَوۡثَرِ',
    numberOfAyahs: 3,
    isMeccan: true,
  },
  {
    id: 109,
    name: 'سُورَةُ الكَافِرُونَ',
    numberOfAyahs: 6,
    isMeccan: true,
  },
  {
    id: 110,
    name: 'سُورَةُ النَّصۡرِ',
    numberOfAyahs: 3,
    isMeccan: false,
  },
  {
    id: 111,
    name: 'سُورَةُ المَسَدِ',
    numberOfAyahs: 5,
    isMeccan: true,
  },
  {
    id: 112,
    name: 'سُورَةُ الإِخۡلَاصِ',
    numberOfAyahs: 4,
    isMeccan: true,
  },
  {
    id: 113,
    name: 'سُورَةُ الفَلَقِ',
    numberOfAyahs: 5,
    isMeccan: true,
  },
  {
    id: 114,
    name: 'سُورَةُ النَّاسِ',
    numberOfAyahs: 6,
    isMeccan: true,
  },
]
